example_app/web/router.ex
defmodule NoegleExampleApp.Router do
  use NoegleExampleApp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Noegle.Plug.CurrentUser
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Noegle.Plug.CurrentUser
    plug Noegle.Plug.RequireAuth
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NoegleExampleApp do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/registration", Noegle.RegistrationController, only: [:new, :create]
    resources "/session", Noegle.SessionController, only: [:new, :create, :delete]
  end

  scope "/", NoegleExampleApp do
    pipe_through :protected

    resources "/secret", SecretController, only: [:index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", NoegleExampleApp do
  #   pipe_through :api
  # end
end

example_app/web/views/layout_view.ex
defmodule NoegleExampleApp.LayoutView do
  use NoegleExampleApp.Web, :view
end

example_app/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Noegle Example App</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li>
              <%= if user = Noegle.Session.current_user(@conn) do %>
                <%= user.name %>
                <%= link "Log out", to: session_path(@conn, :delete, @conn.assigns.current_user), method: :delete %>
              <% end %>
            </li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>